[package]
name = 'uwu'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'uwu'

[dependencies]
extendr-api = '*'
short-uuid = "0.1.2"
uuid = { version = "*", features = ["v4", "v7", "fast-rng"] }
