# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_uwu_wrappers", use_symbols = TRUE, package_name = "uwu")

#' @docType package
#' @usage NULL
#' @useDynLib uwu, .registration = TRUE
NULL

#' Generate new UUIDs
#'
#' Note that if creating a v7 UUID, `uuid::UUIDgenerate(use.time = TRUE, output = "string")` is faster whereas a v4 UUID is ~20x faster using this implementation.
#' @param n the number of uuids to generate
#' @export
new_v4 <- function(n) .Call(wrap__new_v4, n)

#' @export
#' @rdname new_v4
new_v7 <- function(n) .Call(wrap__new_v7, n)

impute_uuid_ <- function(x, prefix) invisible(.Call(wrap__impute_uuid_, x, prefix))

#' Generate new Short UUID
#'
#' @param n the number of short uuids to generate
#' @name short_uuid
#' @export
short_flickr_base58 <- function(n) .Call(wrap__short_flickr_base58, n)

#' @export
#' @rdname short_uuid
short_bitcoin58 <- function(n) .Call(wrap__short_bitcoin58, n)

uuid_flickr_to_short_ <- function(uuid) .Call(wrap__uuid_flickr_to_short_, uuid)

uuid_bitcoin58_to_short_ <- function(uuid) .Call(wrap__uuid_bitcoin58_to_short_, uuid)


# nolint end
